on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Gtk deps
        run: sudo apt update && sudo apt install -y libgtk-3-dev

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
